//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yugioh_AtemReturns
{
    #region Enum

    enum SpriteID
    {

    }

    enum ID
    {

    }

    enum STATUS
    {
        NORMAL,
        DESTROY,
        MOUSEON,
        DEF,
        ATK,      
    }
    #endregion


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class GlobalSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalSetting defaultInstance = ((GlobalSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalSetting())));
        
        public static GlobalSetting Default {
            get {
                return defaultInstance;
            }
        }
    }
}
