//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yugioh_AtemReturns {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class GlobalSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalSetting defaultInstance = ((GlobalSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalSetting())));
        
        public static GlobalSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("740, 425")]
        public global::Microsoft.Xna.Framework.Vector2 PlayerMain {
            get {
                return ((global::Microsoft.Xna.Framework.Vector2)(this["PlayerMain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("735, 330")]
        public global::Microsoft.Xna.Framework.Vector2 PlayerGrave {
            get {
                return ((global::Microsoft.Xna.Framework.Vector2)(this["PlayerGrave"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("330, 310")]
        public global::Microsoft.Xna.Framework.Vector2 PlayerMonF {
            get {
                return ((global::Microsoft.Xna.Framework.Vector2)(this["PlayerMonF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("330, 410")]
        public global::Microsoft.Xna.Framework.Vector2 PlayerSpellF {
            get {
                return ((global::Microsoft.Xna.Framework.Vector2)(this["PlayerSpellF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 0")]
        public global::Microsoft.Xna.Framework.Vector2 HandDistance {
            get {
                return ((global::Microsoft.Xna.Framework.Vector2)(this["HandDistance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("535, 300")]
        public global::Microsoft.Xna.Framework.Vector2 CenterField {
            get {
                return ((global::Microsoft.Xna.Framework.Vector2)(this["CenterField"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("290, 555")]
        public global::Microsoft.Xna.Framework.Vector2 PlayerHand {
            get {
                return ((global::Microsoft.Xna.Framework.Vector2)(this["PlayerHand"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("78, 100")]
        public global::Microsoft.Xna.Framework.Vector2 FieldSlot {
            get {
                return ((global::Microsoft.Xna.Framework.Vector2)(this["FieldSlot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 66")]
        public global::Microsoft.Xna.Framework.Vector2 Phase {
            get {
                return ((global::Microsoft.Xna.Framework.Vector2)(this["Phase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 80")]
        public global::Microsoft.Xna.Framework.Vector2 PhaseSpace {
            get {
                return ((global::Microsoft.Xna.Framework.Vector2)(this["PhaseSpace"]));
            }
        }
    }
}
